---
- hosts: servers
  user: root
  tasks:
  - apt: upgrade=dist
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - yum: name=* state=latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
